
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action fileAction;

	private global::Gtk.Action keluarAction;

	private global::Gtk.Action keluarAction1;

	private global::Gtk.Action keluarAction2;

	private global::Gtk.Action keluarAction3;

	private global::Gtk.Action viewAction;

	private global::Gtk.Action cancelAction;

	private global::Gtk.Action aboutAction;

	private global::Gtk.Action selectColorAction;

	private global::Gtk.Fixed fixed1;

	private global::Gtk.Entry entry1;

	private global::Gtk.Button button;

	private global::Gtk.Button button1;

	private global::Gtk.Button button2;

	private global::Gtk.Button button3;

	private global::Gtk.Button button4;

	private global::Gtk.Button button5;

	private global::Gtk.Button button6;

	private global::Gtk.Button button7;

	private global::Gtk.Button button8;

	private global::Gtk.Button button9;

	private global::Gtk.Button tambah;

	private global::Gtk.Button kurang;

	private global::Gtk.Button perkalian;

	private global::Gtk.Button bagi;

	private global::Gtk.MenuBar menubar1;

	private global::Gtk.Label label1;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.fileAction = new global::Gtk.Action("fileAction", global::Mono.Unix.Catalog.GetString("file"), null, null);
		this.fileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("file");
		w1.Add(this.fileAction, null);
		this.keluarAction = new global::Gtk.Action("keluarAction", global::Mono.Unix.Catalog.GetString("keluar"), null, null);
		this.keluarAction.ShortLabel = global::Mono.Unix.Catalog.GetString("keluar");
		w1.Add(this.keluarAction, null);
		this.keluarAction1 = new global::Gtk.Action("keluarAction1", global::Mono.Unix.Catalog.GetString("keluar"), null, null);
		this.keluarAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("keluar");
		w1.Add(this.keluarAction1, null);
		this.keluarAction2 = new global::Gtk.Action("keluarAction2", global::Mono.Unix.Catalog.GetString("keluar"), null, null);
		this.keluarAction2.ShortLabel = global::Mono.Unix.Catalog.GetString("keluar");
		w1.Add(this.keluarAction2, null);
		this.keluarAction3 = new global::Gtk.Action("keluarAction3", global::Mono.Unix.Catalog.GetString("keluar"), null, null);
		this.keluarAction3.ShortLabel = global::Mono.Unix.Catalog.GetString("keluar");
		w1.Add(this.keluarAction3, null);
		this.viewAction = new global::Gtk.Action("viewAction", global::Mono.Unix.Catalog.GetString("view"), null, null);
		this.viewAction.ShortLabel = global::Mono.Unix.Catalog.GetString("view");
		w1.Add(this.viewAction, null);
		this.cancelAction = new global::Gtk.Action("cancelAction", global::Mono.Unix.Catalog.GetString("Cancel"), null, "gtk-cancel");
		this.cancelAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Cancel");
		w1.Add(this.cancelAction, null);
		this.aboutAction = new global::Gtk.Action("aboutAction", global::Mono.Unix.Catalog.GetString("Donate"), null, "gtk-about");
		this.aboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Donate");
		w1.Add(this.aboutAction, null);
		this.selectColorAction = new global::Gtk.Action("selectColorAction", global::Mono.Unix.Catalog.GetString("about"), null, "gtk-select-color");
		this.selectColorAction.ShortLabel = global::Mono.Unix.Catalog.GetString("about");
		w1.Add(this.selectColorAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entry1 = new global::Gtk.Entry();
		this.entry1.WidthRequest = 335;
		this.entry1.CanFocus = true;
		this.entry1.Name = "entry1";
		this.entry1.IsEditable = true;
		this.entry1.InvisibleChar = '●';
		this.fixed1.Add(this.entry1);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entry1]));
		w2.X = 31;
		w2.Y = 44;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button = new global::Gtk.Button();
		this.button.CanFocus = true;
		this.button.Name = "button";
		this.button.UseUnderline = true;
		this.button.Label = global::Mono.Unix.Catalog.GetString("0");
		this.fixed1.Add(this.button);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button]));
		w3.X = 33;
		w3.Y = 98;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button1 = new global::Gtk.Button();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString("1");
		this.fixed1.Add(this.button1);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button1]));
		w4.X = 69;
		w4.Y = 98;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button2 = new global::Gtk.Button();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString("2");
		this.fixed1.Add(this.button2);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button2]));
		w5.X = 108;
		w5.Y = 99;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button3 = new global::Gtk.Button();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString("3");
		this.fixed1.Add(this.button3);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button3]));
		w6.X = 146;
		w6.Y = 101;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button4 = new global::Gtk.Button();
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString("4");
		this.fixed1.Add(this.button4);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button4]));
		w7.X = 185;
		w7.Y = 100;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button5 = new global::Gtk.Button();
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.Label = global::Mono.Unix.Catalog.GetString("5");
		this.fixed1.Add(this.button5);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button5]));
		w8.X = 33;
		w8.Y = 153;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button6 = new global::Gtk.Button();
		this.button6.CanFocus = true;
		this.button6.Name = "button6";
		this.button6.UseUnderline = true;
		this.button6.Label = global::Mono.Unix.Catalog.GetString("6");
		this.fixed1.Add(this.button6);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button6]));
		w9.X = 68;
		w9.Y = 156;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button7 = new global::Gtk.Button();
		this.button7.CanFocus = true;
		this.button7.Name = "button7";
		this.button7.UseUnderline = true;
		this.button7.Label = global::Mono.Unix.Catalog.GetString("7");
		this.fixed1.Add(this.button7);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button7]));
		w10.X = 109;
		w10.Y = 157;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button8 = new global::Gtk.Button();
		this.button8.CanFocus = true;
		this.button8.Name = "button8";
		this.button8.UseUnderline = true;
		this.button8.Label = global::Mono.Unix.Catalog.GetString("8");
		this.fixed1.Add(this.button8);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button8]));
		w11.X = 145;
		w11.Y = 160;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button9 = new global::Gtk.Button();
		this.button9.CanFocus = true;
		this.button9.Name = "button9";
		this.button9.UseUnderline = true;
		this.button9.Label = global::Mono.Unix.Catalog.GetString("9");
		this.fixed1.Add(this.button9);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button9]));
		w12.X = 183;
		w12.Y = 159;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.tambah = new global::Gtk.Button();
		this.tambah.WidthRequest = 68;
		this.tambah.CanFocus = true;
		this.tambah.Name = "tambah";
		this.tambah.UseUnderline = true;
		this.tambah.Label = global::Mono.Unix.Catalog.GetString("+");
		this.fixed1.Add(this.tambah);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.tambah]));
		w13.X = 234;
		w13.Y = 101;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.kurang = new global::Gtk.Button();
		this.kurang.WidthRequest = 67;
		this.kurang.CanFocus = true;
		this.kurang.Name = "kurang";
		this.kurang.UseUnderline = true;
		this.kurang.Label = global::Mono.Unix.Catalog.GetString("-");
		this.fixed1.Add(this.kurang);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.kurang]));
		w14.X = 234;
		w14.Y = 151;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.perkalian = new global::Gtk.Button();
		this.perkalian.WidthRequest = 79;
		this.perkalian.CanFocus = true;
		this.perkalian.Name = "perkalian";
		this.perkalian.UseUnderline = true;
		this.perkalian.Label = global::Mono.Unix.Catalog.GetString("*");
		this.fixed1.Add(this.perkalian);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.perkalian]));
		w15.X = 229;
		w15.Y = 200;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.bagi = new global::Gtk.Button();
		this.bagi.WidthRequest = 171;
		this.bagi.CanFocus = true;
		this.bagi.Name = "bagi";
		this.bagi.UseUnderline = true;
		this.bagi.Label = global::Mono.Unix.Catalog.GetString("/");
		this.fixed1.Add(this.bagi);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.bagi]));
		w16.X = 36;
		w16.Y = 208;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.UIManager.AddUiFromString(@"<ui><menubar name='menubar1'><menu name='fileAction' action='fileAction'><menuitem name='keluarAction' action='keluarAction'/></menu><menu name='keluarAction1' action='keluarAction1'><menuitem name='keluarAction2' action='keluarAction2'/><menuitem name='keluarAction3' action='keluarAction3'/></menu><menu name='viewAction' action='viewAction'><menuitem name='cancelAction' action='cancelAction'/><menuitem name='aboutAction' action='aboutAction'/><menuitem name='selectColorAction' action='selectColorAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.fixed1.Add(this.menubar1);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.menubar1]));
		w17.X = 8;
		w17.Y = 4;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("kalkulator made with love");
		this.fixed1.Add(this.label1);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label1]));
		w18.X = 90;
		w18.Y = 258;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 488;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
